### ISSUE TITLE
[FEATURE] Allow ability to upload/set logo for dashboard inventory view

### ISSUE THREAD

**Issue by Joshndroid** [l4rm4nd/VoucherVault#27] opened 2024-08-04 23:11 UTC
Within the ~~dashboard~~ inventory view it would be nice to have the primary view be a logo type setup with some of the details still visible with the expiry's (if a gift card) being able to be shown if the item differs from a gift card to a loyalty card.

Proposed I guess is something similar to catima but not quite... which has a card view but this method allows you to easily pick the card based on the logo/brand that you can upload the image as well a differentiate if its a loyalty card/gift card....

![image](https://github.com/user-attachments/assets/764a5f60-66e1-4b2f-8adf-4f561eb6a762)

Catima's is quite small and would not allow you to differentiate between gift cards, loyalty cards, etc easily.

I like the way your inventory dashboard is displayed in mobile.

If you were able to have the background of the card have a logo picture, then have the details overlayed it would assist at a glance at just the dash board in determining what you are looking at using...

With gift cards, an issue/expiry date is shown.
For loyalty cards, no issue/expiry date is shown

I have included a couple example mock ups base on your current mobile view.

![example1](https://github.com/user-attachments/assets/441fb888-ded9-4dff-b58d-7b89c9237f26)
![example2](https://github.com/user-attachments/assets/09f3dded-079a-4b70-bdf5-b71747eb41db)

**Comment by l4rm4nd** [comment] 2024-08-04 23:39
The idea is nice.

Following issues will occur:

- Users upload images with weird resolutions. As the VoucherVault application is responsive, the background images will be rendered differently depending on the client device's height/width. Can look weird.
- Users upload images with an unfitting color theme. The frontend will have a fixed CSS style and render text in a given color (e.g. black). If the user uploads a dark image, text will not or less be visible.
- Users upload images, which are not minimal. For example with big logos, repeating pattern etc. This will disturb the whole tile, which is currently minimalistic and clean.

I could provide some fixed background images for often used stores like Amazon, Steam etc. However, this will not introduce the flexibility you desire and requires maintenance (as many users will request more stores do be added).

Will have to think about this one and play around.

### Examples

A [random Amazon logo](https://cdn.dribbble.com/users/2100764/screenshots/5549172/media/6d36a6fb2cd6e5c2ebb644a4d51c5a95.gif) would currently look like this:

![image](https://github.com/user-attachments/assets/79ae8faa-3642-4235-9fc6-1dfa18ff2159)

A [random Jochen Schweizer logo](https://presse.jochen-schweizer.de/fileadmin/jspr-assets/_processed_/csm_JS_App_300dpi_CMYK_Logo_3608636a1a.jpg):

![image](https://github.com/user-attachments/assets/185e57e1-dcb2-486b-b641-4d824ef2987e)

**Comment by l4rm4nd** [comment] 2024-08-04 23:43
Instead of the QR/EAN13 code displaying, which is rather useless atm, we could introduce a store icon. This would work flawlessly and would be less prone to user errors (choosing a fitting image).

![image](https://github.com/user-attachments/assets/bbf55904-c759-4d25-9b6e-e2abecadc40a)

**Comment by l4rm4nd** [comment] 2024-08-04 23:46
> Instead of the QR/EAN13 code displaying, which is rather useless atm, we could introduce a store icon. This would work flawlessly and would be less prone to user errors (choosing a fitting image).
> 
> I highly assume there are libraries with pre-existing logos we may choose from.
> 
> ![image](https://private-user-images.githubusercontent.com/21357789/354936496-bbf55904-c759-4d25-9b6e-e2abecadc40a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MTUzNDMsIm5iZiI6MTcyMjgxNTA0MywicGF0aCI6Ii8yMTM1Nzc4OS8zNTQ5MzY0OTYtYmJmNTU5MDQtYzc1OS00ZDI1LTliNmUtZTJhYmVjYWRjNDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDIzNDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NTQxMWQxMjM1ZjA3MzcyNzRhOThmZTFhNzljZjFiMTU5ZjdhMWFmZWYwNzJkNWEyNjgxZDViM2YxMjgyZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tkb6bk6B66JQDV0YYvfKdv8llDfQ47Fxb9Vbz1Yrvto)

Guessed right.

https://logo.clearbit.com/amazon.com

https://logo.clearbit.com/google.com

https://logo.clearbit.com/jochen-schweizer.de

**Comment by Joshndroid** [comment] 2024-08-04 23:57
It's your program, however having something predefined and not user uploaded is going to end up just being an all-round pain for you and the users who want some flexibility... there are going to be 10's of thousands of businesses not within any of those predefined logo spaces. You'll end up with a bunch of requests or end up just opening it up, being sick of people asking for X company logo

Is it possible to have guidelines for an appropriately sized image?
Typically your target audience is going to be people who already have a technical ability to run a self hosted application. 
Following some documentation or having a hint in the upload screen would be fairly simple.

I see the update regarding the app icon in the corner over the barcode and once again, its yours program but I don't necessarily enjoy that concept from a visual perspective (i understand it's all subjective)

One other work around could be a 'compact' view for your dashboard sub category inventory view...
User uploaded images that are displayed in a specific dimension in the compact view, which then moves to the box in the corner in general dashboard inventory view
This view could be unlocked in each category... say you have just gift cards.... so in the gift card sub category you have 'compact view' which just shows the user uploaded logo in a 200x300px rectangle with a $ value....
This could be contrasted in the loyalty card view where it just shows the 200x300px user uploaded logo....
it's likely this would end up being a pain probably to code or whatever i can imagine

**Comment by l4rm4nd** [comment] 2024-08-05 00:37
I've created a new branch to play around with this.

https://github.com/l4rm4nd/VoucherVault/tree/feature-logos

Currently, the flexible logos via logo.clearbit.com is implemented. Works as intended by providing the user a chance to define a logo slug.

![image](https://github.com/user-attachments/assets/b57a2748-05b4-4a68-bf71-7fdf6bd5e37d)

**Comment by Joshndroid** [comment] 2024-08-05 01:02
Nice work.
I think there will be a bunch of people who will enjoy this.
I think I like the customization/tinker path a little more.
I will see how this develops and may end up coming back for a look.
Thanks for the responsive chat, your doing some cool stuff

**Comment by l4rm4nd** [comment] 2024-08-05 07:38
Pushed a new release (v1.5.0) with the ability to define store logos.

See https://github.com/l4rm4nd/VoucherVault/pull/28

**Comment by l4rm4nd** [comment] 2024-08-05 09:07
Will close this issue for now as not planned. 

Will still play around though whether custom background images are somehow possible.

**Closed** 2024-08-05 09:07 UTC
Labels: feature request
