### ISSUE TITLE
[FEATURE] Allow expire field to be empty

### ISSUE THREAD

**Issue by TheZoker** [l4rm4nd/VoucherVault#31] opened 2024-08-07 12:24 UTC
**Is your feature request related to a problem? Please describe.**
Not every coupon/voucher has a expiry date, so this field should not be mandatory

**Describe the solution you'd like**
Make expiry field optional

**Describe alternatives you've considered**

**Additional context**

**Comment by l4rm4nd** [comment] 2024-08-07 12:37
Duplicate of #25

**Closed by l4rm4nd** 2024-08-07 12:37 UTC
Labels: feature request
